// libs/react/bismi_allah-tic-tac-toe/src/App.js
//بسم الله الرحمن الرحيم
//la ilaha illa Allah Mohammed Rassoul Allah
import logo from './logo.svg';
import './bismi_allah.css';
import { useState } from 'react';

export default function Board() {
  return (
    <>
      <div className="board-row">
        <Square />
        <Square />
        <Square />
      </div>
      <div className="board-row">
        <Square />
        <Square />
        <Square />
      </div>
      <div className="board-row">
        <Square />
        <Square />
        <Square />
      </div>
    </>
    )
}

//in the name of Allah
function Square() {
  const [value, setValue] = useState(null);

  function handleClick() {
    setValue('X');
  }

  return <button className="square" onClick={handleClick}>{value}</button>;
}

// libs/svelte/subhana_allah/src/App.svelte
<!-- بسم الله الرحمن الرحيم -->
<!-- la ilaha illa Allah Mohammed Rassoul Allah -->

<script>
    import MyButton from './MyButton.svelte';
    import Effects from './Effects.svelte';

    let count = $state(0);
    function increment() {
        count += 1;
    }
    let multiple = $derived(count * 2);
    
    // logs value on change, similar to
    // `console.log($state.snapshot(count))`
    $inspect(count);
    // can also do
    // $inspect(count).with(console.trace);
</script>

<main>
    <MyButton />
    <button onclick={increment}>
        {count}
    </button>
    <p>{multiple}</p>
    <Effects />
</main>

<style>
</style>
